version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    build:
      args:
        - RAILS_ENV=production
    environment:
      - RAILS_ENV=production
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db


