version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    build:
      args:
        - RAILS_ENV=development
    volumes:
      - ./sample_app_rails_4:/myapp
    environment:
      - RAILS_ENV=development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    extra_hosts:
      - "mysql:54.210.120.147"
    depends_on:
      - db

