version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    restart: always
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    image: jenkins:5000/sampleappstagingv2_web
    environment:
      - RAILS_ENV=staging
    restart: always
    extra_hosts:
      - "mysql:54.210.120.147"
    depends_on:
      - db


