version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    image: jenkins:5000/sampleappstaging_web
    environment:
      - RAILS_ENV=staging
    depends_on:
      - db


