version: '2'
services:
  db:
    extends:
      file: docker-compose.common.yml
      service: db
    restart: always
  web:
    extends:
      file: docker-compose.common.yml
      service: web
    image: jenkins:5000/sampleappproductionv2_web
    environment:
      - RAILS_ENV=production
    extra_hosts:
      - "mysql:54.210.120.147"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    restart: always
    depends_on:
      - db


